-- CampoBase · auditoría defensiva de datos deportivos
-- 19/09/2026
-- Aditiva y no destructiva. No modifica payloads deportivos existentes.

create table if not exists public.campobase_datos_historial (
  audit_id bigint generated by default as identity primary key,
  source_table text not null check (source_table in ('partidos','convocatorias','asistencias','configuracion')),
  user_id uuid not null,
  record_id text not null,
  record jsonb not null,
  motivo text not null,
  captured_at timestamptz not null default now()
);

create index if not exists campobase_datos_historial_user_source_record_idx
  on public.campobase_datos_historial (user_id, source_table, record_id, captured_at desc);

alter table public.campobase_datos_historial enable row level security;

drop policy if exists "campobase_historial_select_own" on public.campobase_datos_historial;
create policy "campobase_historial_select_own"
  on public.campobase_datos_historial
  for select
  using (auth.uid() = user_id);

create or replace function public.auditar_campobase_dato()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.campobase_datos_historial (
    source_table,
    user_id,
    record_id,
    record,
    motivo,
    captured_at
  )
  values (
    TG_TABLE_NAME,
    OLD.user_id,
    OLD.id,
    to_jsonb(OLD),
    lower(TG_OP),
    now()
  );

  if TG_OP = 'DELETE' then
    return OLD;
  end if;
  return NEW;
end;
$$;

drop trigger if exists trg_auditar_partidos on public.partidos;
create trigger trg_auditar_partidos
before update or delete on public.partidos
for each row execute function public.auditar_campobase_dato();

drop trigger if exists trg_auditar_convocatorias on public.convocatorias;
create trigger trg_auditar_convocatorias
before update or delete on public.convocatorias
for each row execute function public.auditar_campobase_dato();

drop trigger if exists trg_auditar_asistencias on public.asistencias;
create trigger trg_auditar_asistencias
before update or delete on public.asistencias
for each row execute function public.auditar_campobase_dato();

drop trigger if exists trg_auditar_configuracion on public.configuracion;
create trigger trg_auditar_configuracion
before update or delete on public.configuracion
for each row execute function public.auditar_campobase_dato();

-- Línea base recuperable del estado actual. Se inserta una sola vez por registro.
insert into public.campobase_datos_historial (source_table, user_id, record_id, record, motivo)
select 'partidos', p.user_id, p.id, to_jsonb(p), 'baseline_20260919'
from public.partidos p
where not exists (
  select 1 from public.campobase_datos_historial h
  where h.source_table='partidos' and h.user_id=p.user_id and h.record_id=p.id and h.motivo='baseline_20260919'
);

insert into public.campobase_datos_historial (source_table, user_id, record_id, record, motivo)
select 'convocatorias', c.user_id, c.id, to_jsonb(c), 'baseline_20260919'
from public.convocatorias c
where not exists (
  select 1 from public.campobase_datos_historial h
  where h.source_table='convocatorias' and h.user_id=c.user_id and h.record_id=c.id and h.motivo='baseline_20260919'
);

insert into public.campobase_datos_historial (source_table, user_id, record_id, record, motivo)
select 'asistencias', a.user_id, a.id, to_jsonb(a), 'baseline_20260919'
from public.asistencias a
where not exists (
  select 1 from public.campobase_datos_historial h
  where h.source_table='asistencias' and h.user_id=a.user_id and h.record_id=a.id and h.motivo='baseline_20260919'
);

insert into public.campobase_datos_historial (source_table, user_id, record_id, record, motivo)
select 'configuracion', c.user_id, c.id, to_jsonb(c), 'baseline_20260919'
from public.configuracion c
where not exists (
  select 1 from public.campobase_datos_historial h
  where h.source_table='configuracion' and h.user_id=c.user_id and h.record_id=c.id and h.motivo='baseline_20260919'
);

-- Snapshot explícito de la plantilla validada actual, sin cambiar la tabla jugadores.
insert into public.jugadores_historial (
  user_id,
  jugador_id,
  payload,
  updated_at,
  deleted_at,
  motivo,
  captured_at
)
select
  j.user_id,
  j.id,
  j.payload,
  j.updated_at,
  j.deleted_at,
  'baseline_validada_20260919',
  now()
from public.jugadores j
where j.deleted_at is null
  and not exists (
    select 1
    from public.jugadores_historial h
    where h.user_id=j.user_id
      and h.jugador_id=j.id
      and h.motivo='baseline_validada_20260919'
  );
