-- CampoBase · versiones inmutables y guardas anti-sobrescritura
-- 19/09/2026
-- Protección aditiva: registra cada versión guardada y bloquea escrituras obsoletas.

create table if not exists public.campobase_versiones_datos (
  version_id bigint generated by default as identity primary key,
  source_table text not null check (source_table in ('jugadores','partidos','convocatorias','asistencias','configuracion')),
  user_id uuid not null,
  record_id text not null,
  operation text not null check (operation in ('BASELINE','INSERT','UPDATE','DELETE')),
  record jsonb not null,
  source_updated_at bigint,
  actor_user_id uuid,
  transaction_id bigint not null default txid_current(),
  captured_at timestamptz not null default now()
);

create index if not exists campobase_versiones_user_source_record_idx
  on public.campobase_versiones_datos (user_id, source_table, record_id, captured_at desc);

create index if not exists campobase_versiones_captured_idx
  on public.campobase_versiones_datos (captured_at desc);

alter table public.campobase_versiones_datos enable row level security;

drop policy if exists "campobase_versiones_select_own" on public.campobase_versiones_datos;
create policy "campobase_versiones_select_own"
  on public.campobase_versiones_datos
  for select
  using (auth.uid() = user_id);

revoke insert, update, delete, truncate on public.campobase_versiones_datos from anon, authenticated;
grant select on public.campobase_versiones_datos to authenticated;

create or replace function public.registrar_version_campobase()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  row_data jsonb;
  row_user_id uuid;
  row_id text;
  row_updated_at bigint;
begin
  if TG_OP = 'DELETE' then
    row_data := to_jsonb(OLD);
    row_user_id := OLD.user_id;
    row_id := OLD.id;
    row_updated_at := OLD.updated_at;
  else
    row_data := to_jsonb(NEW);
    row_user_id := NEW.user_id;
    row_id := NEW.id;
    row_updated_at := NEW.updated_at;
  end if;

  insert into public.campobase_versiones_datos (
    source_table,
    user_id,
    record_id,
    operation,
    record,
    source_updated_at,
    actor_user_id,
    transaction_id,
    captured_at
  ) values (
    TG_TABLE_NAME,
    row_user_id,
    row_id,
    TG_OP,
    row_data,
    row_updated_at,
    auth.uid(),
    txid_current(),
    now()
  );

  return coalesce(NEW, OLD);
end;
$$;

create or replace function public.bloquear_escritura_obsoleta_campobase()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if NEW.updated_at < OLD.updated_at then
    raise exception using
      errcode = '40001',
      message = format(
        'CAMPOBASE_STALE_WRITE: %s/%s remoto=%s entrante=%s',
        TG_TABLE_NAME,
        OLD.id,
        OLD.updated_at,
        NEW.updated_at
      );
  end if;
  return NEW;
end;
$$;

create or replace function public.proteger_campos_personales_jugador()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  key text;
  old_profile_updated bigint := coalesce(nullif(OLD.payload->>'profileUpdatedAt','')::bigint, 0);
  new_profile_updated bigint := coalesce(nullif(NEW.payload->>'profileUpdatedAt','')::bigint, 0);
  protected_keys text[] := array[
    'name','number','positions','foot','notes',
    'fatherName','fatherPhone','motherName','motherPhone',
    'photo','createdAt','profileUpdatedAt'
  ];
begin
  if OLD.payload is null or NEW.payload is null then
    return NEW;
  end if;

  if new_profile_updated <= old_profile_updated then
    foreach key in array protected_keys loop
      if OLD.payload ? key then
        NEW.payload := jsonb_set(
          NEW.payload,
          array[key],
          OLD.payload->key,
          true
        );
      else
        NEW.payload := NEW.payload - key;
      end if;
    end loop;
  end if;

  return NEW;
end;
$$;

-- Guardas de servidor: una copia antigua nunca puede vencer a una fila más reciente.
drop trigger if exists trg_bloquear_stale_jugadores on public.jugadores;
create trigger trg_bloquear_stale_jugadores
before update on public.jugadores
for each row execute function public.bloquear_escritura_obsoleta_campobase();

drop trigger if exists trg_bloquear_stale_partidos on public.partidos;
create trigger trg_bloquear_stale_partidos
before update on public.partidos
for each row execute function public.bloquear_escritura_obsoleta_campobase();

drop trigger if exists trg_bloquear_stale_convocatorias on public.convocatorias;
create trigger trg_bloquear_stale_convocatorias
before update on public.convocatorias
for each row execute function public.bloquear_escritura_obsoleta_campobase();

drop trigger if exists trg_bloquear_stale_asistencias on public.asistencias;
create trigger trg_bloquear_stale_asistencias
before update on public.asistencias
for each row execute function public.bloquear_escritura_obsoleta_campobase();

drop trigger if exists trg_bloquear_stale_configuracion on public.configuracion;
create trigger trg_bloquear_stale_configuracion
before update on public.configuracion
for each row execute function public.bloquear_escritura_obsoleta_campobase();

-- Segunda barrera: estadísticas/sync no pueden degradar los campos manuales de una ficha.
drop trigger if exists trg_proteger_campos_personales_jugador on public.jugadores;
create trigger trg_proteger_campos_personales_jugador
before update on public.jugadores
for each row execute function public.proteger_campos_personales_jugador();

-- Versionado AFTER: registra exactamente la versión que quedó guardada.
drop trigger if exists trg_versionar_jugadores on public.jugadores;
create trigger trg_versionar_jugadores
after insert or update or delete on public.jugadores
for each row execute function public.registrar_version_campobase();

drop trigger if exists trg_versionar_partidos on public.partidos;
create trigger trg_versionar_partidos
after insert or update or delete on public.partidos
for each row execute function public.registrar_version_campobase();

drop trigger if exists trg_versionar_convocatorias on public.convocatorias;
create trigger trg_versionar_convocatorias
after insert or update or delete on public.convocatorias
for each row execute function public.registrar_version_campobase();

drop trigger if exists trg_versionar_asistencias on public.asistencias;
create trigger trg_versionar_asistencias
after insert or update or delete on public.asistencias
for each row execute function public.registrar_version_campobase();

drop trigger if exists trg_versionar_configuracion on public.configuracion;
create trigger trg_versionar_configuracion
after insert or update or delete on public.configuracion
for each row execute function public.registrar_version_campobase();

-- Línea base inicial: copia exacta de todas las filas existentes, activas o tombstone.
insert into public.campobase_versiones_datos (
  source_table, user_id, record_id, operation, record, source_updated_at, actor_user_id
)
select 'jugadores', j.user_id, j.id, 'BASELINE', to_jsonb(j), j.updated_at, null
from public.jugadores j
where not exists (
  select 1 from public.campobase_versiones_datos v
  where v.source_table='jugadores' and v.user_id=j.user_id and v.record_id=j.id and v.operation='BASELINE'
);

insert into public.campobase_versiones_datos (
  source_table, user_id, record_id, operation, record, source_updated_at, actor_user_id
)
select 'partidos', p.user_id, p.id, 'BASELINE', to_jsonb(p), p.updated_at, null
from public.partidos p
where not exists (
  select 1 from public.campobase_versiones_datos v
  where v.source_table='partidos' and v.user_id=p.user_id and v.record_id=p.id and v.operation='BASELINE'
);

insert into public.campobase_versiones_datos (
  source_table, user_id, record_id, operation, record, source_updated_at, actor_user_id
)
select 'convocatorias', c.user_id, c.id, 'BASELINE', to_jsonb(c), c.updated_at, null
from public.convocatorias c
where not exists (
  select 1 from public.campobase_versiones_datos v
  where v.source_table='convocatorias' and v.user_id=c.user_id and v.record_id=c.id and v.operation='BASELINE'
);

insert into public.campobase_versiones_datos (
  source_table, user_id, record_id, operation, record, source_updated_at, actor_user_id
)
select 'asistencias', a.user_id, a.id, 'BASELINE', to_jsonb(a), a.updated_at, null
from public.asistencias a
where not exists (
  select 1 from public.campobase_versiones_datos v
  where v.source_table='asistencias' and v.user_id=a.user_id and v.record_id=a.id and v.operation='BASELINE'
);

insert into public.campobase_versiones_datos (
  source_table, user_id, record_id, operation, record, source_updated_at, actor_user_id
)
select 'configuracion', c.user_id, c.id, 'BASELINE', to_jsonb(c), c.updated_at, null
from public.configuracion c
where not exists (
  select 1 from public.campobase_versiones_datos v
  where v.source_table='configuracion' and v.user_id=c.user_id and v.record_id=c.id and v.operation='BASELINE'
);
