-- CampoBase · rate limit para inicio de sesión con PIN
-- 19/09/2026
-- Tabla interna: solo Edge Function con service_role puede escribir/leer.

create table if not exists public.pin_login_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  ip_hash text not null,
  success boolean not null default false,
  attempted_at timestamptz not null default now()
);

create index if not exists pin_login_attempts_user_ip_time_idx
  on public.pin_login_attempts (user_id, ip_hash, attempted_at desc);

create index if not exists pin_login_attempts_user_time_idx
  on public.pin_login_attempts (user_id, attempted_at desc);

alter table public.pin_login_attempts enable row level security;

revoke all on public.pin_login_attempts from anon, authenticated;
revoke all on sequence public.pin_login_attempts_id_seq from anon, authenticated;
